// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SimbaProject.Entities;
using System;

namespace SimbaProject.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20180117214656_TotalBorrowRow")]
    partial class TotalBorrowRow
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimbaProject.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BorrowedCopies");

                    b.Property<string>("Title");

                    b.Property<int>("TotalCopies");

                    b.HasKey("BookId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("SimbaProject.Models.BookReader", b =>
                {
                    b.Property<int>("BookId");

                    b.Property<int>("ReaderId");

                    b.HasKey("BookId", "ReaderId");

                    b.HasIndex("ReaderId");

                    b.ToTable("BookReader");
                });

            modelBuilder.Entity("SimbaProject.Models.Reader", b =>
                {
                    b.Property<int>("ReaderId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrentBorrow");

                    b.Property<int>("Fine");

                    b.Property<string>("Name");

                    b.Property<string>("UserType");

                    b.Property<bool>("VIP");

                    b.HasKey("ReaderId");

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("SimbaProject.Models.BookReader", b =>
                {
                    b.HasOne("SimbaProject.Models.Book", "Book")
                        .WithMany("BookReaders")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SimbaProject.Models.Reader", "Reader")
                        .WithMany("BooksReaders")
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
